language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"

install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"

script: nosetests --tests tests.unit
