language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"

script: nosetests --tests tests.unit --with-coverage --cover-html --cover-html-dir coverage --cover-erase --cover-package grapher

notifications:
  email: false
