language: python
python:
  - "3.3"
  - "3.4"

install:
  - "python setup.py install"
  - "pip install -r tests/requirements-dev.txt"

script: nosetests

after_success:
  coveralls

notifications:
  email:
    on_success: never
    on_failure: change
